Update Copy.java
from Teams:

I edited the code to this:
@ElementCollection(targetClass=String.class)
@MapKeyColumn(name="whoCheckedOut")
private Map<Integer, String> whoCheckedOut;
@ElementCollection(targetClass=String.class)
@MapKeyColumn(name="holder")
private Map<Integer, String> holder;

The issue seems to be solved, but now I'm getting this one:
org.hibernate.MappingException: Repeated column in mapping for collection: com.library.entity.Copy.holder column: holder

Edit:
@ElementCollection(targetClass=String.class)
@MapKeyColumn(name="checked_out_by")
private Map<Integer, String> whoCheckedOut;
@ElementCollection(targetClass=String.class)
@MapKeyColumn(name="holding")

It seems making the name in MapKeyColumn the same as the variable's causes the error.